apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP  # Internal only, act as an internal alb and its cluster ip shall be used as endpoint
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-db
