apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service  # shall serve as an internal load balancer
spec:
  type: ClusterIP
  ports:
  - port: 80   #port used by external clients  
    targetPort: 5000  #port on which the container pod listens. PORT MAPPING IS DONE FROM  80 (EXTERNALLY) -> 5000  (INTERNALLY)
  selector:
    app: flask-backend