apiVersion: v1
kind: Service
metadata:
  name: flask-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: flask-frontend
  ports:
  - port: 80
    targetPort: 4000  #port on which the container pod listens. PORT MAPPING IS DONE FROM  80 (EXTERNALLY) -> 4000  (INTERNALLY)
    protocol: TCP
